### ISSUE TITLE
Enregistrement impossible de la valeur dans le champ "password pour s'authentifier auprès du serveur OAuth Pégase en tant qu'applicatif MDW"

### ISSUE THREAD

**Issue by bhuet-insalyon** [EsupPortail/esup-mdw-pegase#23]
Bonjour, 

Nous rencontrons une erreur lors de la configuration de mondossierweb dans sa version Pégase. 

Une fois rendu dans le menu de configuration de l’application, dans « Pégase Access token » on souhaite renseigner la valeur pour le champ « password pour s'authentifier auprès du serveur OAuth Pégase en tant qu'applicatif MDW ». 
Quand on cherche à valider via le bouton « Enregistrer » rien ne se passe, et le mot de passe n’est pas déversé dans la base de données. 

Or, pour les deux champs précédents, les informations sont bien validées et présentes en base de données. 

Pouvez vous nous aider sur ce sujet s’il vous plaît ? 

N’hésitez pas à revenir vers moi s’il vous faut d’avantage de précisions. 

Bonne journée, 

Benoit HUET
INSA Lyon

**Comment by bhuet-insalyon** [comment]
En complément, la version concernée de mondossierweb est la 1.5.2, et il s'agit d'une installation à partir du fichier ".war".

**Comment by fbordina** [comment]
Bonjour,
vous n'avez peut-être pas défini le paramètre app.secretkey dans le fichier de configuration qui permet de chiffrer/enregistrer le mot de passe en base de données.
Bonne journée.

**Comment by bhuet-insalyon** [comment]
Bonjour, 

Merci beaucoup pour cette précision. Il fallait effectivement que la valeur pour app.secretkey soit renseignée. 

Toutefois, il ne m’était pas encore possible de renseigner de mot de passe. Dans les logs j’avais l’erreur suivante : 

`org.springframework.transaction.TransactionSystemException: Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Error while committing the transaction`
[...]
`Caused by: java.lang.RuntimeException: java.security.InvalidKeyException: Invalid AES key length: 20 bytes`

Le secret que j’avais saisi dans le fichier de configuration faisait 20 caractères, ce qui provoquait l’erreur. Une fois réduit à 16 et le service redémarré, je n’ai plus cette erreur, et il m’est possible de saisir la valeur dans le champ "password pour s'authentifier auprès du serveur OAuth Pégase en tant qu'applicatif MDW" .

Un grand merci pour votre aide. 

Bonne journée,
