### ISSUE TITLE
Problème de correspondance des données affichées et de la session utilisateur ?

### ISSUE THREAD

**Issue by j-kwan** [EsupPortail/esup-mdw-pegase#30]
Bonjour,
Nous rencontrons une problème sur notre MDW Pegase (v2.2.0-SNAPSHOT 05/02/2024 19:45)
Plusieurs étudiants nous ont signalé cette anomalie quand ils sont sur leur dossier WEB, les informations d'un autre numéro et nom d'étudiant qui apparaît en haut à gauche.
C'est comme si les sessions des usagers se mélangeaient.
![mdw_correspondance](https://github.com/user-attachments/assets/0634f181-f700-4930-ad66-20e0fc7afbd9)
Sauriez vous nous indiquer quel est l'origine de ce problème ?
Comment peut-on corriger cela svp ?
Bien à vous,

**Comment by cdubois54** [comment]
Bonjour,

Je regarde ce problème au plus vite, je vous tiens a informé.
En attendant vous pouvez éventuellement décocher l'option permettant d'afficher le nom et prénom au dessus du menu latéral dans l'encart "Affichage" de la vue "Configuration"

Cordialement

**Comment by j-kwan** [comment]
(re) Bonjour,
Merci beaucoup pour cette réponse.
Je viens de décocher l'option en attendant 
Bien à vous,

**Comment by cdubois54** [comment]
Bonjour,

La version 2.2.3 corrige le bug rencontré.
Merci d'avoir remonté ce problème.

Bonne fin de journée
